/**
 * Typed view over the committed competitor-benchmark results: basin vs other
 * optimization crates on matched (solver, problem) cases, recorded as
 * suboptimality-vs-time convergence traces.
 *
 * The JSON is generated by `web/scripts/collect-competitors.ts` (run via
 * `npm run collect:competitors`) from the `trace` harness output — never
 * hand-edited. This module just types it and adds display metadata, reusing
 * the solver/problem vocabulary from `./benchmarks`.
 */

import { PROBLEM_LABELS, SOLVER_LABELS, type Solver } from "./benchmarks";
import rawData from "./competitor-benchmarks.json";

export { PROBLEM_LABELS, SOLVER_LABELS, type Solver };

/** Competing libraries a case is run against. */
export type Library = "basin" | "argmin" | "gomez" | "nlopt";

/** One `(time, suboptimality)` sample on a convergence trace. */
export interface TracePoint {
    /** Wall-clock time since iter 0, nanoseconds (median over reps). */
    tNs: number;
    /** Suboptimality `f(x) − f*`, floored at a small positive value. */
    subopt: number;
}

export interface CompetitorResult {
    solver: Solver;
    problem: string;
    n: number;
    library: Library;
    points: TracePoint[];
}

export interface CompetitorBenchmarks {
    /** ISO date (YYYY-MM-DD) the results were measured. */
    generatedAt: string;
    env: { os: string; arch: string; cpu: string };
    /** Iteration budget the harness capped each solve at. */
    iterations: number;
    results: CompetitorResult[];
}

export const COMPETITOR_BENCHMARKS = rawData as CompetitorBenchmarks;

export const LIBRARY_ORDER: Library[] = ["basin", "argmin", "gomez", "nlopt"];

export const LIBRARY_LABELS: Record<Library, string> = {
    basin: "basin",
    argmin: "argmin",
    gomez: "gomez",
    nlopt: "nlopt",
};

/** Line/legend colors per library, legible on light and dark backgrounds.
 * basin is indigo (its backend-chart `Vec<f64>` hue); argmin is amber;
 * gomez is teal; nlopt is rose. */
export const LIBRARY_COLORS: Record<Library, string> = {
    basin: "#6366f1",
    argmin: "#f59e0b",
    gomez: "#14b8a6",
    nlopt: "#e11d48",
};

/** One curated competitor case. */
export interface CompetitorCase {
    solver: Solver;
    problem: string;
    /** One line on what the case demonstrates. Shown under the card title. */
    blurb: string;
}

/**
 * The curated case set, in display order — all on Rosenbrock so the
 * comparison varies only the algorithm family. Keep in sync with `CASE_ORDER`
 * in `scripts/collect-competitors.ts` and the cases in
 * `crates/competitor-bench/src/bin/trace.rs`.
 */
export const COMPETITOR_CASES: CompetitorCase[] = [
    {
        solver: "gd",
        problem: "rosenbrock",
        blurb: "Steepest descent with a More–Thuente line search — first-order, identical configuration on both sides.",
    },
    {
        solver: "nm",
        problem: "rosenbrock",
        blurb: "Derivative-free Nelder–Mead. basin and argmin run from a bit-identical initial simplex (standard coefficients); gomez and nlopt construct their own simplex with their default coefficients. nlopt's curve is a per-eval best-so-far trace (no per-iteration hook), the others are per-iteration raw cost. The implementations diverge in path and per-iteration cost.",
    },
    {
        solver: "lbfgs",
        problem: "rosenbrock",
        blurb: "Limited-memory BFGS (m = 10) — quasi-Newton; basin and argmin both use a More–Thuente line search; nlopt uses its bundled L-BFGS (no line-search knob exposed). nlopt's curve is a per-eval best-so-far trace; the others are per-iteration raw cost.",
    },
    {
        solver: "newuoa",
        problem: "styblinski",
        blurb: "Powell's model-based derivative-free NEWUOA — the same algorithm in two implementations: basin vs nlopt's LN_NEWUOA, with matched ρ_beg / ρ_end and npt = 2n+1. The only case off Rosenbrock — the multimodal Styblinski–Tang at n = 5 from the origin, where the quadratic-model method has more to chew on and both implementations descend to the global minimum. Both run to natural ρ-convergence (not the iteration cap). nlopt's curve is a per-eval best-so-far trace; basin's is per-iteration.",
    },
];

/** Libraries a case actually has data for, in canonical order. */
export function librariesFor(solver: Solver, problem: string): Library[] {
    return LIBRARY_ORDER.filter((lib) =>
        COMPETITOR_BENCHMARKS.results.some(
            (r) =>
                r.solver === solver &&
                r.problem === problem &&
                r.library === lib,
        ),
    );
}
