/**
 * Typed view over the committed solver-axis benchmark results: basin's five
 * general optimizers head-to-head from several seeded starting points,
 * recorded as suboptimality-vs-wall-clock-time convergence traces under a
 * fixed wall-clock budget per run.
 *
 * The JSON is generated by `web/scripts/collect-solvers.ts` (run via
 * `npm run collect:solvers`) from the `solver_compare` harness output,
 * never hand-edited. This module just types it and adds display metadata.
 *
 * Lives under `data/` because `web/src/lib/solvers.ts` is already taken by
 * the visualizer's knobs module.
 */
import rawData from "./solver-benchmarks.json";

/** The solver lineup, in display order. */
export const SOLVER_ORDER = ["gd", "nm", "bfgs", "lbfgs", "cmaes"] as const;
export type Solver = (typeof SOLVER_ORDER)[number];

/** One `(time, suboptimality)` sample on a convergence trace. */
export interface TracePoint {
    /** Wall-clock time since iter 0, nanoseconds (median over reps). */
    tNs: number;
    /** Suboptimality `f(x) − f*`, floored at a small positive value. */
    subopt: number;
}

export interface SolverResult {
    solver: Solver;
    problem: string;
    n: number;
    /** Seed used to draw the starting point—uniquely identifies a panel
     * within a problem. */
    seed: number;
    /** Starting parameter (length `n`). Sampled uniformly from the
     * problem's domain box using the seed. */
    start: number[];
    /** Wall-clock budget the run was capped at, nanoseconds. */
    budgetNs: number;
    points: TracePoint[];
}

export interface SolverBenchmarks {
    /** ISO date (YYYY-MM-DD) the results were measured. */
    generatedAt: string;
    env: { os: string; arch: string; cpu: string };
    /** Wall-clock budget per (solver, start, rep). */
    budgetNs: number;
    results: SolverResult[];
}

export const SOLVER_BENCHMARKS = rawData as SolverBenchmarks;

export const SOLVER_LABELS: Record<Solver, string> = {
    gd: "Gradient Descent",
    nm: "Nelder–Mead",
    bfgs: "BFGS",
    lbfgs: "L-BFGS",
    cmaes: "CMA-ES",
};

/** Line/legend colors per solver: mid-tone hues legible on both light and
 * dark backgrounds. Distinct from the backend palette (Vec is indigo there)
 * to avoid cross-page color confusion. */
export const SOLVER_COLORS: Record<Solver, string> = {
    gd: "#0ea5e9", // sky
    nm: "#f59e0b", // amber
    bfgs: "#10b981", // emerald
    lbfgs: "#8b5cf6", // violet
    cmaes: "#f43f5e", // rose
};

/** Problem display labels, used in headings. */
export const PROBLEM_LABELS: Record<string, string> = {
    rosenbrock: "Rosenbrock",
};

/** One panel: a (problem, n, seed) configuration the page draws a chart for. */
export interface StartCard {
    problem: string;
    n: number;
    seed: number;
    /** Starting point, length `n`. Shown as a tooltip or aria-label, not as a
     * panel title (high-dim coordinates aren't human-readable). */
    start: number[];
    /** Cost at the starting point, used as the panel subtitle so the reader
     * can compare difficulty across seeds at a glance. */
    f0: number;
}

/** Every `(problem, seed)` configuration the harness ran, in emission order. */
export const STARTS: StartCard[] = (() => {
    const seen = new Map<string, StartCard>();
    for (const r of SOLVER_BENCHMARKS.results) {
        const key = `${r.problem}|${r.seed}`;
        if (!seen.has(key)) {
            seen.set(key, {
                problem: r.problem,
                n: r.n,
                seed: r.seed,
                start: r.start,
                // `subopt` at iter 0 (t=0) equals `f(x₀) − f*`; we floor it at
                // 1e-10 in the harness, but f(x₀) is always well above that
                // for these starts so this reads cleanly as f(x₀) when
                // f* = 0 (Rosenbrock).
                f0: r.points[0]?.subopt ?? NaN,
            });
        }
    }
    return [...seen.values()];
})();

/** Panels grouped by problem, in the order they appear in the data. Each
 * problem gets its own `<section>` on the page; adding a new problem to the
 * harness shows up here without code changes. */
export interface ProblemSection {
    problem: string;
    label: string;
    n: number;
    panels: StartCard[];
}
export const BY_PROBLEM: ProblemSection[] = (() => {
    const groups = new Map<string, StartCard[]>();
    for (const s of STARTS) {
        if (!groups.has(s.problem)) groups.set(s.problem, []);
        groups.get(s.problem)!.push(s);
    }
    return [...groups.entries()].map(([problem, panels]) => ({
        problem,
        label: PROBLEM_LABELS[problem] ?? problem,
        n: panels[0]?.n ?? 0,
        panels,
    }));
})();

/** One chart series per solver that ran on `(problem, seed)`, in canonical
 * order. Shape matches `ConvergenceChart`'s `series` prop. */
export function seriesFor(problem: string, seed: number) {
    return SOLVER_ORDER.flatMap((solver) => {
        const r = SOLVER_BENCHMARKS.results.find(
            (r) =>
                r.solver === solver && r.problem === problem && r.seed === seed,
        );
        return r
            ? [
                  {
                      label: SOLVER_LABELS[solver],
                      color: SOLVER_COLORS[solver],
                      points: r.points,
                  },
              ]
            : [];
    });
}
