[package]
name = "basin-backend-newer"
version = "0.0.0"
edition = "2024"
publish = false

[features]
lapack = ["basin/nalgebra_v0_35-lapack"]

[dependencies]
basin = { path = "../../../..", features = ["nalgebra_v0_35", "ndarray_v0_17", "faer_v0_24"] }
nalgebra = "0.35"
ndarray = "0.17"
faer = { version = "0.24", default-features = false, features = ["std", "linalg"] }
