version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "nalgebra"
      - dependency-name: "nalgebra-sparse"
      - dependency-name: "nalgebra-lapack"
      - dependency-name: "ndarray"
      - dependency-name: "faer"
  - package-ecosystem: "uv"
    directory: "/tools/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/web/"
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns:
          - "*"
