[package]
name = "basin-backend-older"
version = "0.0.0"
edition = "2024"
publish = false

[features]
lapack = ["basin/nalgebra_v0_32-lapack"]

[dependencies]
basin = { path = "../../../..", features = ["nalgebra_v0_32", "ndarray_v0_15", "faer_v0_22"] }
nalgebra = "0.32"
ndarray = "0.15"
faer = { version = "0.22", default-features = false, features = ["std", "linalg"] }
